version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    networks:
      - experiment
    ports:
      - 18081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - db
    networks:
      - experiment
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/temp:/opt/sonarqube/temp
  db:
    image: postgres
    networks:
      - experiment
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data

  shields:
    image: shieldsio/shields:next
    depends_on:
      - sonarqube
      - jenkins
    networks:
      - experiment
    environment:
      JENKINS_ORIGINS: "https://jenkins:8080"
      JENKINS_USER: admin
      JENKINS_PASS: password
    ports:
      - 18080:80
    command: node server
#    volumes:
#      - ./shields:/usr/src/app

networks:
  experiment:
    driver: bridge
